// Surface 2 — Playground (paste .fct, see compiled output)

const GO_TEMPLATE_OUT = `{{define "action_bar"}}
<div data-fct="ab_a1b2c3"
     class="action-bar"
     data-state="{{.State}}">
  {{template "like_button" (dict
      "PostID" .PostID
      "Liked"  .Liked
      "Count"  .LikeCount)}}
  {{template "bookmark_button" (dict
      "PostID"      .PostID
      "Bookmarked"  .Bookmarked
      "Count"       .BookmarkCount)}}
  <span data-live="view_count_update">
    {{.ViewCount}} views
  </span>
</div>
{{end}}`;

const GO_STRUCT_OUT = `// generated by fctc · DO NOT EDIT
package facets

type ActionBarInput struct {
    PostID        uuid.UUID
    Liked         bool
    LikeCount     int
    BookmarkCount int
    CanReply      bool
}

func RenderActionBar(w io.Writer,
    d ActionBarInput) error {
    return tmpl.ExecuteTemplate(
        w, "action_bar", d)
}`;

const CSS_OUT = `/* generated · scoped */
[data-fct="ab_a1b2c3"] .action-bar {
    display: flex;
    gap: 1rem;
}
[data-fct="ab_a1b2c3"]
    .action-bar[data-state="disabled"] {
    opacity: 0.5;
}`;

function PlaygroundV1() {
  const [tab, setTab] = React.useState('go');
  return (
    <Frame
      title="fct.dev / playground"
      subtitle="https://play.fct.dev/p/abc123"
      kind="window"
      tags={['go-html', 'compile: 18ms']}
      style={{ height: 580 }}
    >
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 220px 1fr', flex: 1, minHeight: 0 }}>
        <div style={{ display: 'flex', flexDirection: 'column', borderRight: '1.5px dashed var(--ink)', minHeight: 0 }}>
          <div className="mono" style={{ fontSize: 11, padding: '4px 10px', borderBottom: '1px dashed var(--ink)', color: 'var(--muted)' }}>
            INPUT · .fct
          </div>
          <CodeBlock height="100%">{FCT_SOURCE_ACTION_BAR}</CodeBlock>
        </div>

        {/* AST tree */}
        <div style={{ borderRight: '1.5px dashed var(--ink)', padding: '6px 10px', minHeight: 0, overflow: 'auto', fontSize: 11.5 }} className="mono">
          <div style={{ fontSize: 10, color: 'var(--muted)', marginBottom: 6 }}>AST</div>
          <div style={{ lineHeight: 1.7 }}>
            <div>▾ FacetFile</div>
            <div style={{ paddingLeft: 12 }}>▾ Contract</div>
            <div style={{ paddingLeft: 24, color: 'var(--muted)' }}>name "action_bar"</div>
            <div style={{ paddingLeft: 24 }}>▾ Inputs · 5</div>
            <div style={{ paddingLeft: 36, color: 'var(--accent)' }}>PostID : uuid !</div>
            <div style={{ paddingLeft: 36 }}>Liked : bool</div>
            <div style={{ paddingLeft: 36 }}>LikeCount : int</div>
            <div style={{ paddingLeft: 36 }}>BookmarkCount : int</div>
            <div style={{ paddingLeft: 36, color: 'var(--accent)' }}>CanReply : bool !</div>
            <div style={{ paddingLeft: 24 }}>▸ States · 2</div>
            <div style={{ paddingLeft: 24 }}>▸ Emits · 4</div>
            <div style={{ paddingLeft: 24 }}>▸ Receives · 1</div>
            <div style={{ paddingLeft: 24 }}>▸ Children · 2</div>
            <div style={{ paddingLeft: 12 }}>▾ Template</div>
            <div style={{ paddingLeft: 24 }}>▾ Element div.action-bar</div>
            <div style={{ paddingLeft: 36, color: 'var(--accent-2)' }}>FacetCall like_button</div>
            <div style={{ paddingLeft: 36, color: 'var(--accent-2)' }}>FacetCall bookmark_btn</div>
            <div style={{ paddingLeft: 36 }}>Element span.live</div>
            <div style={{ paddingLeft: 12 }}>▾ Style</div>
            <div style={{ paddingLeft: 24, color: 'var(--muted)' }}>2 rules, scoped</div>
          </div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', minHeight: 0 }}>
          <div style={{ display: 'flex', borderBottom: '1px dashed var(--ink)' }}>
            {[['go', 'go template'], ['struct', 'struct.go'], ['css', 'scoped.css']].map(([k, l]) => (
              <button
                key={k} onClick={() => setTab(k)}
                style={{
                  background: tab === k ? 'var(--hi)' : 'transparent',
                  border: 'none', borderRight: '1px dashed var(--ink)',
                  fontFamily: 'JetBrains Mono, monospace', fontSize: 11,
                  padding: '4px 10px', cursor: 'pointer',
                  color: tab === k ? 'var(--ink)' : 'var(--muted)',
                }}>{l}</button>
            ))}
          </div>
          <CodeBlock height="100%" lang={tab === 'css' ? 'css' : 'go'}>
            {tab === 'go' ? GO_TEMPLATE_OUT : tab === 'struct' ? GO_STRUCT_OUT : CSS_OUT}
          </CodeBlock>
        </div>
      </div>
      <div style={{ borderTop: '1.5px dashed var(--ink)', padding: '4px 10px', display: 'flex', gap: 14, fontSize: 11, alignItems: 'center' }} className="mono">
        <span className="dot green"></span>
        <span>compiled ok</span>
        <span style={{ color: 'var(--muted)' }}>· 1 facet · 5 inputs · 4 emits · 2 children</span>
        <span style={{ marginLeft: 'auto' }}>
          <span className="chip blue" style={{ fontSize: 10 }}>share /p/abc123</span>
        </span>
      </div>
    </Frame>
  );
}

function PlaygroundV2() {
  // vertical waterfall — pipeline as actual visualisation
  const Stage = ({ n, label, sub, children }) => (
    <div style={{ display: 'flex', gap: 10, alignItems: 'stretch' }}>
      <div style={{ width: 28, display: 'flex', flexDirection: 'column', alignItems: 'center', paddingTop: 8 }}>
        <div className="sbox thin" style={{
          width: 22, height: 22, borderRadius: '50%', display: 'flex',
          alignItems: 'center', justifyContent: 'center',
          fontFamily: 'JetBrains Mono, monospace', fontSize: 11, fontWeight: 700,
        }}>{n}</div>
        <div style={{ flex: 1, borderLeft: '2px dashed var(--ink)', marginTop: 4, minHeight: 10 }} />
      </div>
      <div style={{ flex: 1, paddingBottom: 12 }}>
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
          <div className="scrawl" style={{ fontSize: 20, fontWeight: 700 }}>{label}</div>
          <div className="mono" style={{ color: 'var(--muted)', fontSize: 10 }}>{sub}</div>
        </div>
        <div style={{ marginTop: 4 }}>{children}</div>
      </div>
    </div>
  );

  return (
    <Frame
      title="fctc pipeline"
      subtitle="parse → resolve → check → codegen"
      kind="window"
      tags={['waterfall']}
      style={{ height: 580 }}
      alt
    >
      <div style={{ overflow: 'auto', flex: 1, padding: '10px 14px', minHeight: 0 }}>
        <Stage n="1" label="parse" sub="html5ever · 4 blocks">
          <div className="mono" style={{ fontSize: 11, color: 'var(--muted)', display: 'flex', gap: 6, flexWrap: 'wrap' }}>
            <span className="chip">&lt;fct:contract&gt;</span>
            <span className="chip">&lt;fct:template&gt;</span>
            <span className="chip">&lt;fct:style scoped&gt;</span>
            <span className="chip" style={{ opacity: 0.5 }}>&lt;fct:script&gt;</span>
          </div>
        </Stage>
        <Stage n="2" label="resolve" sub="children → facet graph">
          <div className="mono" style={{ fontSize: 11, lineHeight: 1.6 }}>
            <div>action_bar →</div>
            <div style={{ paddingLeft: 14 }}>like_button <span style={{ color: 'var(--muted)' }}>(inputs ok)</span></div>
            <div style={{ paddingLeft: 14 }}>bookmark_button <span style={{ color: 'var(--muted)' }}>(inputs ok)</span></div>
          </div>
        </Stage>
        <Stage n="3" label="contract check" sub="types · required · refs">
          <div className="mono" style={{ fontSize: 11, color: 'var(--muted)' }}>
            ✓ all required inputs declared<br/>
            ✓ states reference only inputs<br/>
            ✓ no cycles · depth 2
          </div>
        </Stage>
        <Stage n="4" label="codegen · go-html" sub="3 files emitted">
          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
            <div className="sbox thin" style={{ padding: 6, fontFamily: 'JetBrains Mono, monospace', fontSize: 10, flex: '1 1 0' }}>
              <div style={{ color: 'var(--muted)' }}>partials/action_bar.html</div>
              <div>{'<div data-fct=… …>'}</div>
              <div>{'  {{template "like_btn" …}}'}</div>
              <div>{'</div>'}</div>
            </div>
            <div className="sbox thin" style={{ padding: 6, fontFamily: 'JetBrains Mono, monospace', fontSize: 10, flex: '1 1 0' }}>
              <div style={{ color: 'var(--muted)' }}>facets/action_bar.go</div>
              <div>type ActionBarInput struct {'{ ... }'}</div>
              <div>func RenderActionBar(…) error</div>
            </div>
            <div className="sbox thin" style={{ padding: 6, fontFamily: 'JetBrains Mono, monospace', fontSize: 10, flex: '1 1 0' }}>
              <div style={{ color: 'var(--muted)' }}>css/action_bar.css</div>
              <div>[data-fct="ab_a1b2c3"] .action-bar</div>
              <div>{'{ display: flex; gap: 1rem; }'}</div>
            </div>
          </div>
        </Stage>
        <Stage n="5" label="preview" sub="rendered with mock data">
          <div className="sbox thin" style={{ padding: 12, background: 'var(--paper-2)' }}>
            <div style={{ display: 'flex', gap: 14, alignItems: 'center' }}>
              <span className="chip accent">♥ 12</span>
              <span className="chip">🔖 3</span>
              <span className="mono" style={{ fontSize: 11, color: 'var(--muted)' }}>2,341 views</span>
              <span className="chip yellow mono" style={{ marginLeft: 'auto', fontSize: 10 }}>data-fct="ab_a1b2c3"</span>
            </div>
          </div>
        </Stage>
      </div>
    </Frame>
  );
}

function PlaygroundV3() {
  return (
    <Frame
      title="fct.dev / playground"
      subtitle="preview-first"
      kind="window"
      tags={['mock data']}
      style={{ height: 580 }}
    >
      <div style={{ display: 'flex', flexDirection: 'column', flex: 1, minHeight: 0 }}>
        {/* big preview */}
        <div style={{ padding: 16, borderBottom: '1.5px dashed var(--ink)', background: 'var(--paper-2)', position: 'relative' }}>
          <div className="mono" style={{ fontSize: 10, color: 'var(--muted)', marginBottom: 6 }}>RENDERED · live mock data</div>
          <div className="sbox thin" style={{ padding: 14, background: 'var(--paper)' }}>
            <div style={{ display: 'flex', gap: 12, alignItems: 'center', fontSize: 13 }}>
              <span style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                <span style={{ color: 'var(--accent)' }}>♥</span> <b>12</b>
              </span>
              <span style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                <span style={{ color: 'var(--muted)' }}>💬</span> <b>4</b>
              </span>
              <span style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                <span style={{ color: 'var(--muted)' }}>🔖</span> <b>3</b>
              </span>
              <span style={{ marginLeft: 'auto', color: 'var(--muted)', fontFamily: 'JetBrains Mono, monospace', fontSize: 11 }}>2,341 views</span>
            </div>
          </div>
          <Pin style={{ top: 10, right: 14 }}>this is what F33D3R sees</Pin>
          <div className="anno" style={{ position: 'absolute', bottom: -4, left: 20 }}>
            ↑ replace any input below — preview updates instantly
          </div>
        </div>

        {/* mock data row */}
        <div style={{ padding: '8px 14px', borderBottom: '1.5px dashed var(--ink)' }}>
          <div className="mono" style={{ fontSize: 10, color: 'var(--muted)', marginBottom: 4 }}>MOCK INPUTS</div>
          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', fontFamily: 'JetBrains Mono, monospace', fontSize: 11 }}>
            <span className="chip">PostID = abc-123</span>
            <span className="chip">Liked = <b>true</b></span>
            <span className="chip">LikeCount = <b>12</b></span>
            <span className="chip">BookmarkCount = <b>3</b></span>
            <span className="chip">CanReply = <b>true</b></span>
            <span className="chip">ViewCount = <b>2341</b></span>
          </div>
        </div>

        {/* source/output split below */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', flex: 1, minHeight: 0 }}>
          <div style={{ borderRight: '1.5px dashed var(--ink)', display: 'flex', flexDirection: 'column', minHeight: 0 }}>
            <div className="mono" style={{ fontSize: 11, padding: '4px 10px', borderBottom: '1px dashed var(--ink)', color: 'var(--muted)' }}>
              .fct source
            </div>
            <CodeBlock height="100%">{FCT_SOURCE_ACTION_BAR}</CodeBlock>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', minHeight: 0 }}>
            <div className="mono" style={{ fontSize: 11, padding: '4px 10px', borderBottom: '1px dashed var(--ink)', color: 'var(--muted)', display: 'flex', gap: 10 }}>
              <span>compiled go template</span>
              <span style={{ marginLeft: 'auto', color: 'var(--accent-2)' }}>diff vs last build</span>
            </div>
            <CodeBlock height="100%" lang="go">{GO_TEMPLATE_OUT}</CodeBlock>
          </div>
        </div>
      </div>
    </Frame>
  );
}

window.PlaygroundV1 = PlaygroundV1;
window.PlaygroundV2 = PlaygroundV2;
window.PlaygroundV3 = PlaygroundV3;
