import Foundation

/// The canonical JSON writer for Malkuth content addressing.
///
/// This is hand-rolled rather than `JSONEncoder` on purpose, and the reason is
/// the whole point of the file: the bytes are hashed, so any disagreement with
/// the server about ordering or escaping is not a formatting difference, it is a
/// rejected post with the opaque message `cid mismatch`.
///
/// `JSONEncoder` is wrong for this job in two independent ways:
///
/// 1. **Order.** The bytes are ordered by the Go struct's *declaration* order,
///    which is what `json.Marshal` emits. Today that order and `.sortedKeys`
///    lexicographic order happen to be identical — the Go author arranged the
///    fields alphabetically on purpose, and every adjacent pair was checked:
///    `parent_cid < poll_ends_at < poll_options`,
///    `video_duration_secs < video_master_url < video_poster_url`,
///    `video_* < voice_*` (`d` < `i`), `voice_duration_secs < voice_url`.
///    But that is a coincidence being maintained by hand on the other side of a
///    network boundary, and the day someone appends a field to the struct
///    without re-alphabetising it, `.sortedKeys` silently starts producing a
///    different hash for every post. So the order is written out literally here
///    and `MalkuthCanonicalTests` asserts both facts separately: that this
///    encoder emits the declaration order, and that the declaration order is
///    still the sorted order. The second assertion failing is a warning; the
///    first failing is a bug.
///
/// 2. **Escaping.** Go's `json.Encoder` with `SetEscapeHTML(false)` has a
///    specific escape alphabet that no Swift encoder reproduces (see
///    ``escape(_:into:)``). U+2028 in particular is escaped by Go *even with
///    HTML escaping off*, which the browser client's `JSON.stringify` does not
///    do — a real divergence between the two existing clients, resolved here in
///    Go's favour because Go is the verifier.
///
/// Every rule below was read out of `feed-engine/internal/handler/work_event.go`
/// and then confirmed byte-for-byte against output generated by that same Go, in
/// `Fixtures/malkuth_canonical.json`.
public enum CanonicalJSON {

    /// One JSON value, restricted to the shapes the canonical payload can hold.
    ///
    /// A closed enum rather than `Any` because the server's field types are
    /// closed too: a value that is not one of these could not have come from
    /// `workCanonicalPayload`, and would fail verification on the far side
    /// rather than here.
    public enum Value: Equatable, Sendable {
        case string(String)
        case bool(Bool)
        /// Integers only. Go re-marshals `interface{}` numbers through
        /// `float64`, so a value outside ±2^53 would not survive the server's
        /// round trip; `WorkPayload` validation rejects those before they reach
        /// here, and `timestamp_ms` is `int64` in the Go struct so it is exact.
        case int(Int64)
        case null
        case array([Value])
    }

    /// Writes `fields` as a compact JSON object **in the order given**.
    ///
    /// No whitespace, no trailing newline: Go builds the same bytes with
    /// `json.Encoder` and then strips the newline `Encode` appends.
    public static func object(_ fields: [(String, Value)]) -> Data {
        var out = [UInt8]()
        out.reserveCapacity(512)
        out.append(UInt8(ascii: "{"))
        for (index, field) in fields.enumerated() {
            if index > 0 { out.append(UInt8(ascii: ",")) }
            write(.string(field.0), into: &out)
            out.append(UInt8(ascii: ":"))
            write(field.1, into: &out)
        }
        out.append(UInt8(ascii: "}"))
        return Data(out)
    }

    private static func write(_ value: Value, into out: inout [UInt8]) {
        switch value {
        case .string(let s):
            out.append(UInt8(ascii: "\""))
            escape(s, into: &out)
            out.append(UInt8(ascii: "\""))
        case .bool(let b):
            out.append(contentsOf: Array((b ? "true" : "false").utf8))
        case .int(let i):
            out.append(contentsOf: Array(String(i).utf8))
        case .null:
            out.append(contentsOf: Array("null".utf8))
        case .array(let items):
            out.append(UInt8(ascii: "["))
            for (index, item) in items.enumerated() {
                if index > 0 { out.append(UInt8(ascii: ",")) }
                write(item, into: &out)
            }
            out.append(UInt8(ascii: "]"))
        }
    }

    /// Escapes a string body exactly as Go's `json.Encoder` does with
    /// `SetEscapeHTML(false)`.
    ///
    /// The alphabet, confirmed empirically against go1.26 and pinned by the
    /// `control_chars_body`, `backspace_and_formfeed_body`,
    /// `line_separator_body` and `html_chars_body` fixtures:
    ///
    /// | input | output |
    /// |---|---|
    /// | `"` `\` | `\"` `\\` |
    /// | U+0008 U+0009 U+000A U+000C U+000D | `\b` `\t` `\n` `\f` `\r` |
    /// | other U+0000–U+001F | `\u00xx`, **lower-case** hex |
    /// | U+2028 U+2029 | `\u2028` `\u2029` |
    /// | `&` `<` `>` `/` U+007F | **raw** — this is what `SetEscapeHTML(false)` buys |
    /// | everything else | raw UTF-8, never `\uXXXX` |
    ///
    /// Two notes on things that look like omissions and are not:
    ///
    /// - `\b` and `\f` are short escapes here. They were `\u0008` / `\u000c` in
    ///   Go before 1.22. This encoder targets the Go the server is built with
    ///   (`golang:latest`), which is also what `JSON.stringify` does, so the two
    ///   existing clients agree on this one.
    /// - Go has a branch that emits `\ufffd` for invalid UTF-8. It is
    ///   unreachable from here: a Swift `String` cannot hold invalid UTF-8, so
    ///   `String.utf8` is always well-formed.
    private static func escape(_ s: String, into out: inout [UInt8]) {
        let bytes = Array(s.utf8)
        var i = 0
        var runStart = 0

        @inline(__always)
        func flushRun(upTo end: Int) {
            if end > runStart { out.append(contentsOf: bytes[runStart..<end]) }
        }

        while i < bytes.count {
            let b = bytes[i]

            if b < 0x20 {
                flushRun(upTo: i)
                switch b {
                case 0x08: out.append(contentsOf: Array("\\b".utf8))
                case 0x09: out.append(contentsOf: Array("\\t".utf8))
                case 0x0A: out.append(contentsOf: Array("\\n".utf8))
                case 0x0C: out.append(contentsOf: Array("\\f".utf8))
                case 0x0D: out.append(contentsOf: Array("\\r".utf8))
                default:
                    out.append(contentsOf: Array("\\u00".utf8))
                    out.append(hexDigit(b >> 4))
                    out.append(hexDigit(b & 0x0F))
                }
                i += 1
                runStart = i
                continue
            }

            if b == 0x22 || b == 0x5C {  // " and \
                flushRun(upTo: i)
                out.append(UInt8(ascii: "\\"))
                out.append(b)
                i += 1
                runStart = i
                continue
            }

            // U+2028 / U+2029 are E2 80 A8 / E2 80 A9 in UTF-8. Go escapes both
            // unconditionally, independently of SetEscapeHTML.
            if b == 0xE2, i + 2 < bytes.count, bytes[i + 1] == 0x80,
               bytes[i + 2] == 0xA8 || bytes[i + 2] == 0xA9 {
                flushRun(upTo: i)
                out.append(contentsOf: Array(
                    bytes[i + 2] == 0xA8 ? "\\u2028".utf8 : "\\u2029".utf8
                ))
                i += 3
                runStart = i
                continue
            }

            i += 1
        }
        flushRun(upTo: bytes.count)
    }

    private static func hexDigit(_ nibble: UInt8) -> UInt8 {
        nibble < 10 ? UInt8(ascii: "0") + nibble : UInt8(ascii: "a") + (nibble - 10)
    }
}
