import SwiftUI
import F33D3RKit

/// A fresh set of single-use sign-in codes.
///
/// The codes are generated by the server when this sheet opens and shown once.
/// There is no "show them again" — the whole point of a backup code is that the
/// server keeps a hash and nobody, including F33D3R, can read one back. Asking
/// again generates a new set and retires the old one.
///
/// Used from two places: the two-factor sheet, where it is a deliberate
/// refresh, and the gate an account hits when the server refuses to let it do
/// anything until backup codes exist. Same sheet either way — the second one
/// used to send people to Safari with no session, which is a link to a sign-in
/// page pretending to be a setup flow.
struct BackupCodesSheet: View {
    @Environment(AppModel.self) private var model
    @Environment(\.dismiss) private var dismiss

    /// Called after the server has issued a set, so a gate can let the reader
    /// through without them having to find their way back themselves.
    var onIssued: (() -> Void)?

    @State private var codes: [String] = []
    @State private var isLoading = true
    @State private var error: String?
    @State private var didCopy = false

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: F33Spacing.lg) {
                    if isLoading {
                        HStack(spacing: F33Spacing.md) {
                            ProgressView()
                            Text("Generating codes…")
                                .font(.callout)
                                .foregroundStyle(F33Color.ink4)
                        }
                        .frame(maxWidth: .infinity, minHeight: 220)
                    } else if !codes.isEmpty {
                        Text("Keep these somewhere safe. Each one signs you in once, and this is the only time they're shown.")
                            .font(.callout)
                            .foregroundStyle(F33Color.ink3)
                            .fixedSize(horizontal: false, vertical: true)

                        grid

                        Button {
                            UIPasteboard.general.string = codes.joined(separator: "\n")
                            didCopy = true
                        } label: {
                            Label(didCopy ? "Copied" : "Copy all", systemImage: didCopy ? "checkmark" : "doc.on.doc")
                                .font(.callout.weight(.semibold))
                                .foregroundStyle(F33Color.accent)
                                .frame(maxWidth: .infinity, minHeight: F33Layout.minTouchTarget)
                        }
                        .buttonStyle(.plain)
                    } else if let error {
                        // The server's own words. A deployment with no
                        // generator behind the event says so here rather than
                        // the app deciding on its behalf that the feature is
                        // missing.
                        EmptyStateView(
                            icon: "key.horizontal",
                            title: "Couldn't generate codes",
                            message: error,
                            actionTitle: "Try again",
                            action: { Task { await load() } }
                        )
                    }
                }
                .padding(.horizontal, F33Spacing.xl)
                .padding(.vertical, F33Spacing.lg)
                .frame(maxWidth: .infinity, alignment: .leading)
            }
            .background(F33Color.bg)
            .navigationTitle("Backup codes")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") { dismiss() }
                }
            }
        }
        .tint(F33Color.accent)
        .task { await load() }
    }

    private var grid: some View {
        LazyVGrid(columns: [GridItem(.flexible()), GridItem(.flexible())], spacing: F33Spacing.sm) {
            ForEach(codes, id: \.self) { code in
                Text(code)
                    .font(.system(size: 15, weight: .medium, design: .monospaced))
                    .foregroundStyle(F33Color.ink)
                    .frame(maxWidth: .infinity, minHeight: 40)
                    .background(F33Color.bgElevated, in: RoundedRectangle(cornerRadius: F33Radius.sm))
                    .textSelection(.enabled)
            }
        }
    }

    private func load() async {
        isLoading = true
        error = nil
        defer { isLoading = false }
        do {
            codes = try await model.twoFactorBackupCodes()
            if !codes.isEmpty { onIssued?() }
        } catch let error as MalkuthError {
            self.error = error.description
        } catch let error as APIError {
            self.error = error.userMessage
        } catch {
            self.error = error.localizedDescription
        }
    }
}
