import Foundation
import CryptoKit
import Testing
@testable import F33D3RKit

/// Proves this client's signatures are the ones the Go verifier accepts.
///
/// A signature this client makes and then verifies with its own public key
/// proves nothing about the server: every self-consistent bug — signing the
/// payload instead of the CID, DER instead of P1363, standard base64 instead of
/// base64url — passes a self-check and fails `verifyMalkuthSig`. So the proof
/// here runs across the boundary, in both directions:
///
/// **Go to Swift, checked in and run on every `swift test`.**
/// `Fixtures/malkuth_signatures.json` carries signatures produced *by Go*, over
/// CIDs, with keys generated by Go, exported the way the server's key authority
/// stores them. Swift parses the SPKI, decodes the base64url P1363 signature and
/// verifies it. If CryptoKit and `crypto/ecdsa` disagreed about any of the three
/// encodings, this fails.
///
/// **Swift to Go, run once and recorded.**
/// The same fixture carries a Swift-generated key and Swift-made signatures that
/// were fed to a Go program running `verifyMalkuthSig`'s steps 2–6 verbatim
/// (`decodedByGo` / `verifiedByGo`). Swift cannot re-run that here — Go is not
/// available inside `swift test` — so the fixture records what the Go answered
/// and this suite re-derives everything about the vector that *is* checkable:
/// that the recorded SPKI is the SPKI this code exports for that private key,
/// and that the recorded signature verifies. If either drifts, the recorded Go
/// verdict no longer describes what this client produces, and the test says so.
///
/// The fixture also carries **negative** vectors — a signature over a tampered
/// CID, a DER-encoded signature, a padded base64 signature — that Go was asked
/// to verify and *refused*. A cross-check where everything passes is a
/// cross-check that might not be running.
struct MalkuthSignatureTests {

    // MARK: Fixture

    struct SignatureFixture: Decodable {
        let note: String
        let goVersion: String
        /// Vectors Go produced. Swift must verify all of them.
        let fromGo: [Vector]
        /// Vectors Swift produced and Go was asked to verify.
        let fromSwift: [SwiftVector]

        enum CodingKeys: String, CodingKey {
            case note
            case goVersion = "go_version"
            case fromGo = "from_go"
            case fromSwift = "from_swift"
        }
    }

    struct Vector: Decodable {
        let name: String
        let publicKeySPKIB64: String
        let cid: String
        let signatureB64URL: String
        /// Whether the signature is expected to verify. False vectors are the
        /// point: they pin the failures, not just the successes.
        let shouldVerify: Bool

        enum CodingKeys: String, CodingKey {
            case name, cid
            case publicKeySPKIB64 = "public_key_spki_b64"
            case signatureB64URL = "signature_b64url"
            case shouldVerify = "should_verify"
        }
    }

    struct SwiftVector: Decodable {
        let name: String
        /// The raw P-256 private scalar, so the exact key can be rebuilt and the
        /// SPKI re-derived. Test material only — a real signing key never leaves
        /// the Keychain.
        let privateKeyRawB64: String
        let publicKeySPKIB64: String
        let cid: String
        let signatureB64URL: String
        let shouldVerify: Bool
        /// What the Go verifier actually answered when handed this vector.
        let verifiedByGo: Bool

        enum CodingKeys: String, CodingKey {
            case name, cid
            case privateKeyRawB64 = "private_key_raw_b64"
            case publicKeySPKIB64 = "public_key_spki_b64"
            case signatureB64URL = "signature_b64url"
            case shouldVerify = "should_verify"
            case verifiedByGo = "verified_by_go"
        }
    }

    static func fixture() throws -> SignatureFixture {
        try JSONDecoder().decode(
            SignatureFixture.self, from: try ContractTests.fixture("malkuth_signatures")
        )
    }

    /// Verifies the way the server does: parse SPKI, decode raw base64url,
    /// require 64 bytes, treat it as `r||s`, check against SHA-256 of the CID's
    /// UTF-8 bytes. Written out rather than reusing `MalkuthKey.verify` so the
    /// test does not verify with the same code path that signed.
    static func verifyLikeServer(
        publicKeySPKIB64: String, cid: String, signatureB64URL: String
    ) -> Bool {
        guard let spki = Data(base64Encoded: publicKeySPKIB64),
              let key = try? P256.Signing.PublicKey(derRepresentation: spki)
        else { return false }
        guard let raw = Base64URL.decodeStrict(signatureB64URL), raw.count == 64,
              let signature = try? P256.Signing.ECDSASignature(rawRepresentation: raw)
        else { return false }
        return key.isValidSignature(signature, for: Data(cid.utf8))
    }

    // MARK: Go to Swift

    @Test("Signatures Go made verify here, and the ones Go should refuse do not")
    func verifiesGoSignatures() throws {
        let fixture = try Self.fixture()
        #expect(!fixture.fromGo.isEmpty)

        for vector in fixture.fromGo {
            let verified = Self.verifyLikeServer(
                publicKeySPKIB64: vector.publicKeySPKIB64,
                cid: vector.cid,
                signatureB64URL: vector.signatureB64URL
            )
            #expect(
                verified == vector.shouldVerify,
                "\(vector.name): expected verify=\(vector.shouldVerify), got \(verified)"
            )
        }

        // The negative vectors have to actually be there, or the assertion above
        // is satisfied by a fixture that only contains easy cases.
        #expect(fixture.fromGo.contains { !$0.shouldVerify })
    }

    // MARK: Swift to Go

    @Test("The vectors Go verified are still the vectors this client produces")
    func swiftVectorsStillDescribeThisClient() throws {
        let fixture = try Self.fixture()
        #expect(!fixture.fromSwift.isEmpty)

        for vector in fixture.fromSwift {
            // Go's verdict is what the fixture recorded. Anything else means the
            // cross-verification run itself was wrong.
            #expect(
                vector.verifiedByGo == vector.shouldVerify,
                "\(vector.name): Go answered \(vector.verifiedByGo), expected \(vector.shouldVerify)"
            )

            // The SPKI in the fixture must be the SPKI this code exports for
            // that key. If `publicKeySPKIBase64` ever changed encoding — to
            // x963, say — Go's recorded "yes" would be about a key this client
            // no longer sends.
            let raw = try #require(Data(base64Encoded: vector.privateKeyRawB64))
            let key = try MalkuthKey(rawPrivateKey: raw)
            #expect(key.publicKeySPKIBase64 == vector.publicKeySPKIB64, "\(vector.name): SPKI drifted")

            // And the signature must still be one this key's public half accepts
            // over these exact bytes.
            let verifiesHere = Self.verifyLikeServer(
                publicKeySPKIB64: vector.publicKeySPKIB64,
                cid: vector.cid,
                signatureB64URL: vector.signatureB64URL
            )
            #expect(verifiesHere == vector.shouldVerify, "\(vector.name)")
        }

        #expect(fixture.fromSwift.contains { !$0.shouldVerify })
    }

    // MARK: The three encoding traps, stated directly

    @Test("A signature is 64 raw bytes of r||s, never DER")
    func signsInP1363() throws {
        let key = MalkuthKey.generate()
        let cid = "sha256:" + String(repeating: "ab", count: 32)
        let signature = try key.signature(forContentID: cid)

        let decoded = try #require(Base64URL.decode(signature))
        // `verifyMalkuthSig` rejects anything that is not exactly 64 bytes
        // before it ever tries to verify.
        #expect(decoded.count == 64)

        // A DER signature is 70-72 bytes and starts with SEQUENCE (0x30). This
        // is what using `derRepresentation` would have produced.
        #expect(decoded.first != 0x30 || decoded.count == 64)
    }

    @Test("base64url, unpadded — Go decodes with RawURLEncoding and refuses the rest")
    func encodesSignatureAsRawBase64URL() throws {
        let key = MalkuthKey.generate()
        // 64 bytes is not a multiple of 3, so standard base64 pads: this is not
        // a hypothetical case, every signature would carry a trailing "=".
        let signature = try key.signature(forContentID: "sha256:" + String(repeating: "0", count: 64))
        #expect(!signature.contains("="))
        #expect(!signature.contains("+"))
        #expect(!signature.contains("/"))
        #expect(signature.count == 86)  // ceil(64 * 4 / 3) with no padding
    }

    @Test("The signed message is the CID string, not the payload and not the digest")
    func signsTheCIDString() throws {
        let key = MalkuthKey.generate()
        let payload = WorkPayload(
            authorPIAL: MalkuthCanonicalTests.pial, body: "what is signed", timestampMS: 1
        )
        let envelope = try WorkEnvelope(payload: payload, key: key)

        // Verifying against the CID's UTF-8 bytes succeeds...
        #expect(Self.verifyLikeServer(
            publicKeySPKIB64: key.publicKeySPKIBase64,
            cid: envelope.contentID,
            signatureB64URL: envelope.signature
        ))

        // ...and against the canonical payload bytes, or against the raw digest,
        // it does not. Both are plausible mistakes and both would be silent.
        let spki = try #require(Data(base64Encoded: key.publicKeySPKIBase64))
        let publicKey = try P256.Signing.PublicKey(derRepresentation: spki)
        let raw = try #require(Base64URL.decode(envelope.signature))
        let parsed = try P256.Signing.ECDSASignature(rawRepresentation: raw)

        #expect(!publicKey.isValidSignature(parsed, for: envelope.canonicalPayload))

        let digestBytes = Data(SHA256.hash(data: envelope.canonicalPayload))
        #expect(!publicKey.isValidSignature(parsed, for: digestBytes))
    }

    @Test("The exported public key is SPKI DER, which is what ParsePKIXPublicKey reads")
    func exportsSPKI() throws {
        let key = MalkuthKey.generate()
        let der = try #require(Data(base64Encoded: key.publicKeySPKIBase64))

        // SPKI for a P-256 key is a 91-byte SEQUENCE. The uncompressed point
        // (`x963Representation`) is 65 bytes starting 0x04 — the shape that
        // would make `x509.ParsePKIXPublicKey` fail.
        #expect(der.count == 91)
        #expect(der.first == 0x30)
        // Round-trips back to a key.
        #expect((try? P256.Signing.PublicKey(derRepresentation: der)) != nil)
    }

    @Test("A padded or standard-alphabet signature is not accepted as base64url")
    func rejectsPaddedSignature() throws {
        let key = MalkuthKey.generate()
        let cid = "sha256:" + String(repeating: "cd", count: 32)
        let signature = try key.signature(forContentID: cid)

        // What `base64.RawURLEncoding.DecodeString` does with padding: refuse.
        #expect(Base64URL.decodeStrict(signature + "=") == nil)
        // And with the standard alphabet, when the signature happens to contain
        // a character that differs between the two.
        let standard = try #require(Base64URL.decode(signature)).base64EncodedString()
        if standard.contains("+") || standard.contains("/") {
            #expect(Base64URL.decodeStrict(standard.replacingOccurrences(of: "=", with: "")) == nil)
        }
    }

    // MARK: Export

    /// Writes fresh Swift-made vectors for the Go verifier.
    ///
    /// Skipped unless `MALKUTH_EXPORT_DIR` is set, because it is not a test — it
    /// is the first half of a cross-verification whose second half runs in Go.
    /// Re-run it, feed the output to the verifier, and replace the `from_swift`
    /// half of the fixture with what comes back.
    @Test(
        "Export Swift signature vectors for the Go verifier",
        .enabled(if: ProcessInfo.processInfo.environment["MALKUTH_EXPORT_DIR"] != nil)
    )
    func exportVectorsForGo() throws {
        let directory = try #require(ProcessInfo.processInfo.environment["MALKUTH_EXPORT_DIR"])
        let key = MalkuthKey.generate()
        let raw = key.rawPrivateKey
        let spki = key.publicKeySPKIBase64

        // Real CIDs, from the canonical fixtures, so the vectors sign the same
        // strings a real post would.
        let cids = try MalkuthCanonicalTests.golden().cases.prefix(6).map(\.cid)

        var vectors: [[String: Any]] = []
        for (index, cid) in cids.enumerated() {
            vectors.append([
                "name": "swift_signed_\(index)",
                "private_key_raw_b64": raw.base64EncodedString(),
                "public_key_spki_b64": spki,
                "cid": cid,
                "signature_b64url": try key.signature(forContentID: cid),
                "should_verify": true,
            ])
        }

        // Negative: a valid signature presented against a different CID. Go must
        // refuse it, and a Go that accepts it is a Go verifying the wrong bytes.
        let goodCID = try #require(cids.first)
        vectors.append([
            "name": "swift_signed_wrong_cid",
            "private_key_raw_b64": raw.base64EncodedString(),
            "public_key_spki_b64": spki,
            "cid": "sha256:" + String(repeating: "ff", count: 32),
            "signature_b64url": try key.signature(forContentID: goodCID),
            "should_verify": false,
        ])

        // Negative: the DER form of a real signature. Fails Go's length check.
        let derSignature = try P256.Signing.PrivateKey(rawRepresentation: raw)
            .signature(for: Data(goodCID.utf8))
        vectors.append([
            "name": "swift_signed_der_form",
            "private_key_raw_b64": raw.base64EncodedString(),
            "public_key_spki_b64": spki,
            "cid": goodCID,
            "signature_b64url": Base64URL.encode(derSignature.derRepresentation),
            "should_verify": false,
        ])

        // Negative: padded base64url. Fails Go's RawURLEncoding decode.
        vectors.append([
            "name": "swift_signed_padded_base64",
            "private_key_raw_b64": raw.base64EncodedString(),
            "public_key_spki_b64": spki,
            "cid": goodCID,
            "signature_b64url": try key.signature(forContentID: goodCID) + "=",
            "should_verify": false,
        ])

        let url = URL(fileURLWithPath: directory).appendingPathComponent("vectors_from_swift.json")
        let data = try JSONSerialization.data(
            withJSONObject: ["vectors": vectors], options: [.prettyPrinted, .sortedKeys]
        )
        try data.write(to: url)
        print("[malkuth] wrote \(vectors.count) vectors to \(url.path)")
    }
}

extension Base64URL {
    /// base64url decoding with Go's `RawURLEncoding` strictness: the URL-safe
    /// alphabet, and padding is an error rather than something to be tolerated.
    ///
    /// ``Base64URL/decode(_:)`` is deliberately lenient because it reads values
    /// this client may have written before the rule was pinned; this one exists
    /// to assert what the server will accept.
    static func decodeStrict(_ string: String) -> Data? {
        guard !string.contains("="), !string.contains("+"), !string.contains("/") else {
            return nil
        }
        return decode(string)
    }
}
