import Foundation
import Testing
@testable import F33D3RKit

/// Proves the Swift canonical encoder reproduces the Go one, byte for byte.
///
/// This is the only kind of proof worth having here. "It compiles" is worth
/// nothing and self-consistency is worth less than nothing: an encoder that
/// agrees with itself and disagrees with the server produces a `cid mismatch`
/// on every post, and the server does not say which byte.
///
/// `Fixtures/malkuth_canonical.json` is generated by running
/// `workCanonicalPayload` and `verifyCID` — copied verbatim out of
/// `feed-engine/internal/handler/work_event.go` — over a set of payloads
/// covering every field shape. The generator additionally asserts, for each
/// case, that the bytes are a **fixed point** of the server's own
/// unmarshal-then-re-marshal: the server does not hash what the client sent, it
/// hashes what it gets back from `json.Unmarshal` into `workCanonicalPayload`,
/// where `interface{}` numbers have become `float64` and `poll_options` has
/// become `[]interface{}`. Bytes that survive that round trip are bytes the
/// server will hash to the same CID.
struct MalkuthCanonicalTests {

    // MARK: Fixture loading

    struct GoldenFile: Decodable {
        let generatedBy: String
        let cases: [Case]
        enum CodingKeys: String, CodingKey {
            case generatedBy = "generated_by"
            case cases
        }
    }

    struct Case: Decodable {
        let name: String
        let note: String
        let input: Input
        /// The canonical JSON as text, for a readable diff when a case fails.
        let canonical: String
        /// The same bytes, base64. Authoritative: a JSON string cannot carry a
        /// lone control byte through two decoders without ambiguity, and these
        /// cases contain several on purpose.
        let canonicalB64: String
        let cid: String

        enum CodingKeys: String, CodingKey {
            case name, note, input, canonical, cid
            case canonicalB64 = "canonical_b64"
        }

        var canonicalBytes: Data { Data(base64Encoded: canonicalB64)! }
    }

    /// The payload in natural types, exactly as the generator described it.
    /// `mediaURLs` here is the *unsorted* input: sorting is part of what the
    /// client under test has to do.
    struct Input: Decodable {
        let authorPIAL: String
        let body: String
        let commentGating: String
        let isRepost: Bool
        let kind: String
        let mediaURLs: [String]
        let parentCID: String?
        let pollEndsAt: String?
        let pollOptions: [String]?
        let repostSourceID: String?
        let scheduledAt: String?
        let subscriberOnly: Bool
        let tags: [String]
        let timestampMS: Int64
        let videoDurationSecs: Int?
        let videoMasterURL: String?
        let videoPosterURL: String?
        let voiceDurationSecs: Int?
        let voiceURL: String?

        enum CodingKeys: String, CodingKey {
            case authorPIAL = "author_pial"
            case body
            case commentGating = "comment_gating"
            case isRepost = "is_repost"
            case kind
            case mediaURLs = "media_urls"
            case parentCID = "parent_cid"
            case pollEndsAt = "poll_ends_at"
            case pollOptions = "poll_options"
            case repostSourceID = "repost_source_id"
            case scheduledAt = "scheduled_at"
            case subscriberOnly = "subscriber_only"
            case tags
            case timestampMS = "timestamp_ms"
            case videoDurationSecs = "video_duration_secs"
            case videoMasterURL = "video_master_url"
            case videoPosterURL = "video_poster_url"
            case voiceDurationSecs = "voice_duration_secs"
            case voiceURL = "voice_url"
        }

        /// The payload this input describes. Deliberately goes through the
        /// public initialiser: the test exercises the type a compose screen
        /// would build, not a private back door.
        func payload() throws -> WorkPayload {
            let kind = try #require(WorkKind(rawValue: kind), "unknown kind in fixture: \(kind)")
            let gating = try #require(
                CommentGating(rawValue: commentGating),
                "unknown comment_gating in fixture: \(commentGating)"
            )
            return WorkPayload(
                authorPIAL: authorPIAL,
                body: body,
                commentGating: gating,
                isRepost: isRepost,
                kind: kind,
                mediaURLs: mediaURLs,
                parentCID: parentCID,
                pollEndsAt: pollEndsAt,
                pollOptions: pollOptions,
                repostSourceID: repostSourceID,
                scheduledAt: scheduledAt,
                subscriberOnly: subscriberOnly,
                tags: tags,
                timestampMS: timestampMS,
                videoDurationSecs: videoDurationSecs,
                videoMasterURL: videoMasterURL,
                videoPosterURL: videoPosterURL,
                voiceDurationSecs: voiceDurationSecs,
                voiceURL: voiceURL
            )
        }
    }

    static func golden() throws -> GoldenFile {
        let data = try ContractTests.fixture("malkuth_canonical")
        return try JSONDecoder().decode(GoldenFile.self, from: data)
    }

    // MARK: The proof

    @Test("Every golden payload encodes to the exact bytes Go produced")
    func reproducesGoCanonicalBytes() throws {
        let golden = try Self.golden()
        #expect(!golden.cases.isEmpty)

        for testCase in golden.cases {
            let payload = try testCase.input.payload()
            let produced = payload.canonicalJSON()
            let expected = testCase.canonicalBytes

            if produced != expected {
                Issue.record("""
                    \(testCase.name) — \(testCase.note)
                      go:    \(String(decoding: expected, as: UTF8.self))
                      swift: \(String(decoding: produced, as: UTF8.self))
                      first difference at byte \(Self.firstDifference(expected, produced).map(String.init) ?? "?")
                    """)
            }
        }
    }

    @Test("Every golden payload hashes to the CID Go computed")
    func reproducesGoCIDs() throws {
        for testCase in try Self.golden().cases {
            let payload = try testCase.input.payload()
            #expect(payload.contentID() == testCase.cid, "\(testCase.name)")
            #expect(ContentID.isWellFormed(testCase.cid), "\(testCase.name)")
        }
    }

    /// A fixture set that quietly stopped covering something is worse than no
    /// fixture set, because it still passes. These are the shapes the contract
    /// has, named so that removing one from the generator fails here.
    @Test("The fixtures still cover every field shape that matters")
    func fixtureCoverageIsComplete() throws {
        let names = Set(try Self.golden().cases.map(\.name))
        let required = [
            "empty_body_post", "plain_post",
            "html_chars_body", "unicode_body", "emoji_body",
            "control_chars_body", "backspace_and_formfeed_body", "line_separator_body",
            "no_media", "one_media", "several_media_unsorted", "media_sort_is_bytewise",
            "reply", "quote", "poll", "poll_empty_options_array",
            "repost", "scheduled", "scheduled_with_offset",
            "voice", "voice_zero_duration", "video", "react_video", "thread_post",
            "empty_tags", "populated_tags",
            "gating_followers", "gating_none", "gating_circle", "subscriber_only",
            "everything_at_once", "timestamp_boundaries", "solidus_and_quotes",
        ]
        for name in required {
            #expect(names.contains(name), "fixture \(name) is gone — regenerate from the Go")
        }

        // Every kind in the closed vocabulary is exercised by at least one case,
        // so a kind added to `workKinds` without a fixture is visible here.
        let kinds = Set(try Self.golden().cases.map(\.input.kind))
        for kind in WorkKind.allCases {
            #expect(kinds.contains(kind.rawValue), "no fixture uses kind \(kind.rawValue)")
        }
        let gatings = Set(try Self.golden().cases.map(\.input.commentGating))
        for gating in CommentGating.allCases {
            #expect(gatings.contains(gating.rawValue), "no fixture uses gating \(gating.rawValue)")
        }
    }

    // MARK: Ordering

    /// The declaration order of `workCanonicalPayload`, read off the Go struct.
    static let declaredOrder = [
        "author_pial", "body", "comment_gating", "is_repost", "kind", "media_urls",
        "parent_cid", "poll_ends_at", "poll_options", "repost_source_id", "scheduled_at",
        "subscriber_only", "tags", "timestamp_ms", "video_duration_secs",
        "video_master_url", "video_poster_url", "voice_duration_secs", "voice_url",
    ]

    @Test("The encoder emits the Go struct's declaration order")
    func emitsDeclarationOrder() {
        let payload = WorkPayload(authorPIAL: Self.pial, timestampMS: 0)
        #expect(payload.canonicalFields().map(\.0) == Self.declaredOrder)
    }

    /// A warning, not a contract. `.sortedKeys` is *not* what this encoder does,
    /// and this test exists so that the day someone appends a field to the Go
    /// struct without re-alphabetising it, that fact is announced here rather
    /// than discovered by a client that trusted `.sortedKeys` and now hashes
    /// different bytes than the server.
    @Test("Declaration order is still lexicographic order")
    func declarationOrderIsStillSorted() {
        #expect(Self.declaredOrder == Self.declaredOrder.sorted())
    }

    @Test("The order in the golden bytes is the order the encoder emits")
    func goldenBytesCarryDeclarationOrder() throws {
        let bytes = try #require(try Self.golden().cases.first).canonicalBytes
        let text = String(decoding: bytes, as: UTF8.self)
        var searchFrom = text.startIndex
        for key in Self.declaredOrder {
            let needle = "\"\(key)\":"
            let found = try #require(
                text.range(of: needle, range: searchFrom..<text.endIndex),
                "\(key) is missing or out of order in the Go output"
            )
            searchFrom = found.upperBound
        }
    }

    // MARK: Escaping, stated as rules rather than only as fixtures

    /// Go's escape alphabet, stated as rules.
    ///
    /// The fixtures pin these too, but a fixture failure says only "these bytes
    /// differ". This says which character.
    @Test("Go's escape alphabet, character by character")
    func escapesLikeGo() {
        let cases: [(body: String, expected: String)] = [
            ("a & b", "a & b"),                  // SetEscapeHTML(false): raw
            ("<script>", "<script>"),            // raw
            ("a/b", "a/b"),                      // solidus never escaped
            ("say \"hi\"", #"say \"hi\""#),
            ("back\\slash", #"back\\slash"#),
            ("\u{08}", #"\b"#),
            ("\u{09}", #"\t"#),
            ("\u{0A}", #"\n"#),
            ("\u{0C}", #"\f"#),
            ("\u{0D}", #"\r"#),
            ("\u{00}", #"\u0000"#),
            ("\u{01}", #"\u0001"#),
            ("\u{0B}", #"\u000b"#),              // lower-case hex, always four digits
            ("\u{1F}", #"\u001f"#),
            ("\u{7F}", "\u{7F}"),                // DEL is in Go's safeSet: raw
            ("\u{2028}", #"\u2028"#),            // escaped even with escapeHTML off
            ("\u{2029}", #"\u2029"#),
            ("\u{E9}", "\u{E9}"),                // never \uXXXX
            ("\u{1F703}", "\u{1F703}"),          // astral plane: raw UTF-8
        ]
        for (body, expected) in cases {
            let text = String(decoding: CanonicalJSON.object([("b", .string(body))]), as: UTF8.self)
            #expect(text == "{\"b\":\"\(expected)\"}", "body \(body.unicodeScalars.map { String($0.value, radix: 16) })")
        }
    }

    @Test("Booleans, integers and nulls have no whitespace and no surprises")
    func writesScalars() {
        let encoded = CanonicalJSON.object([
            ("t", .bool(true)), ("f", .bool(false)), ("n", .null),
            ("zero", .int(0)), ("neg", .int(-1)),
            ("big", .int(9_007_199_254_740_993)),
            ("empty", .array([])),
        ])
        #expect(String(decoding: encoded, as: UTF8.self) ==
                #"{"t":true,"f":false,"n":null,"zero":0,"neg":-1,"big":9007199254740993,"empty":[]}"#)
    }

    // MARK: The two normalisations

    @Test("media_urls is sorted by UTF-8 byte, the way Go's sort.Strings is")
    func sortsMediaURLsLikeGo() {
        // Swift's own `<` on String is Unicode canonical ordering and would put
        // these differently; Go compares bytes.
        let input = ["/z.webp", "/A.webp", "/a.webp", "/Z.webp", "/é.webp", "/_.webp"]
        #expect(WorkPayload.sortedByUTF8(input) ==
                ["/A.webp", "/Z.webp", "/_.webp", "/a.webp", "/z.webp", "/é.webp"])

        // A string that is a prefix of another sorts first, as byte comparison
        // requires and as Swift's default would not necessarily give.
        #expect(WorkPayload.sortedByUTF8(["ab", "a"]) == ["a", "ab"])
    }

    @Test("Sorting media_urls does not reorder tags")
    func doesNotSortTags() {
        var payload = WorkPayload(authorPIAL: Self.pial, timestampMS: 0)
        payload.tags = ["zeta", "alpha", "Mixed"]
        payload.mediaURLs = ["/z", "/a"]
        let text = String(decoding: payload.canonicalJSON(), as: UTF8.self)
        #expect(text.contains(#""media_urls":["/a","/z"]"#))
        #expect(text.contains(#""tags":["zeta","alpha","Mixed"]"#))
    }

    @Test("Empty collections are [] and absent optionals are null, never omitted")
    func distinguishesEmptyFromNull() {
        var payload = WorkPayload(authorPIAL: Self.pial, timestampMS: 0)
        payload.pollOptions = []
        let withEmpty = String(decoding: payload.canonicalJSON(), as: UTF8.self)
        #expect(withEmpty.contains(#""media_urls":[]"#))
        #expect(withEmpty.contains(#""tags":[]"#))
        #expect(withEmpty.contains(#""poll_options":[]"#))

        payload.pollOptions = nil
        let withNull = String(decoding: payload.canonicalJSON(), as: UTF8.self)
        #expect(withNull.contains(#""poll_options":null"#))
        #expect(withNull.contains(#""parent_cid":null"#))
        #expect(withNull.contains(#""voice_url":null"#))

        // The two are genuinely different works.
        #expect(withEmpty != withNull)
    }

    @Test("Every field appears exactly once, even when nil")
    func emitsEveryFieldAlways() {
        let text = String(
            decoding: WorkPayload(authorPIAL: Self.pial, timestampMS: 0).canonicalJSON(),
            as: UTF8.self
        )
        for key in Self.declaredOrder {
            let occurrences = text.components(separatedBy: "\"\(key)\":").count - 1
            #expect(occurrences == 1, "\(key) appears \(occurrences) times")
        }
    }

    // MARK: Helpers

    static let pial = "3f2504e0-4f89-11d3-9a0c-0305e82c3301"

    static func firstDifference(_ a: Data, _ b: Data) -> Int? {
        for index in 0..<Swift.min(a.count, b.count) where a[index] != b[index] { return index }
        return a.count == b.count ? nil : Swift.min(a.count, b.count)
    }
}
