[package]
name = "abraxas-core"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "abraxas-core"
path = "src/main.rs"

[dependencies]
rdkafka = { version = "0", features = ["cmake-build", "ssl"] }
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0", features = ["with-uuid-1", "with-serde_json-1", "with-chrono-0_4"] }
deadpool-postgres = { version = "0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
tracing = "0"
tracing-subscriber = { version = "0", features = ["json", "env-filter"] }
chrono = { version = "0", features = ["serde"] }
