package handler

import (
	"context"
	"log"
	"net/http"
	"net/url"
	"strings"
	"time"

	dbpkg "github.com/f33d3r/feed-engine/internal/db"
)

// ── The Number lane of the messaging surface ─────────────────────────────────
//
// Messages has always had exactly one way in: an @handle. This file adds the
// second, alongside it and never in place of it — a F33D3R Number.
//
// Nothing here decides anything. The decision belongs to elohim-veni and is
// taken through the one entry point this brain has, evaluateContact. The
// conversation is opened through ensureDirectConversation, the same function the
// @handle path uses, so there is exactly one way a conversation comes into
// existence. Messages then fan out through the existing gnosis_message stream
// and contact requests through the existing notification pipeline.
//
// What this file owns is the SURFACE: the shape of the Number a person typed,
// and the honest rendering of every outcome the authority can return.

// ── The shape of a Number ────────────────────────────────────────────────────
//
// The definition lives in manhattan/src/number.rs, which is AUTHORITATIVE for
// this format. What follows is a hand-written mirror of it: twelve decimal
// digits, the twelfth a Luhn check digit over the other eleven, rendered
// 0412-8837-2919 and spoken 0412 8837 2919.
//
// Two implementations of one format is a standing drift risk, so the drift is
// not guarded by care — it is guarded mechanically. manhattan/number.conformance
// is generated by the Rust definition and read by this package's own tests, so a
// mirror that disagrees about one digit, one separator, one folded letter or one
// check rule fails its own suite. See zz_messages_number_test.go.
//
// Validating the shape at this edge is the same doctrine Manhattan applies one
// hop further in — nine of every ten blind guesses cost arithmetic instead of
// I/O — except that here it costs no HTTP hop either, because a Number refused
// on this line never leaves the process. It is also what lets a genuine typing
// mistake be named as one.
//
// Numbers minted before the digit format keep working for ever: thirteen
// Crockford base32 symbols with a mod-37 check symbol. The two shapes are
// disjoint by length and cannot be confused. Nothing here mints; minting is
// Manhattan's, and every new Number is digits.
//
// Naming a malformed Number leaks nothing. Length, alphabet and check digit are
// a pure function of what the caller typed; anyone can compute them offline
// without this service. What must never be named is why a WELL-FORMED Number did
// not reach anyone, and no path below ever names that.

const (
	// What a person reads aloud: eleven payload digits and one check digit.
	numberTotalLen = 12
	// Crockford base32, for Numbers minted before the digit format. The five
	// check-only symbols are never valid in a presented Number — a legacy
	// Number containing U is malformed, not unknown.
	numberLegacyAlphabet      = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
	numberLegacyCheckAlphabet = "0123456789ABCDEFGHJKMNPQRSTVWXYZ*~$=U"
	numberLegacyPayloadLen    = 12
	numberLegacyTotalLen      = 13
	numberNamespace           = "number"
	// A Number is twelve digits; separators and the namespace prefix cannot
	// plausibly quintuple that. Anything longer is refused without being scanned.
	numberInputMax = 64
)

// foldNumberSymbol applies Crockford's confusable folding: I and L read as 1, O
// reads as 0. A Number heard aloud and written down by hand must still resolve,
// and a twelve-digit Number containing an O is a 0 somebody drew badly — not a
// different Number and not an attack. The folded result is still digits.
func foldNumberSymbol(b byte) byte {
	if b >= 'a' && b <= 'z' {
		b -= 'a' - 'A'
	}
	switch b {
	case 'I', 'L':
		return '1'
	case 'O':
		return '0'
	}
	return b
}

// isNumberSeparator reports whether a byte is punctuation between groups.
// Spaces and hyphens are what a Number is printed with; underscores and full
// stops are what people actually type. None of them carry meaning.
//
// A leading + is deliberately NOT one. It is what a pasted telephone number
// begins with, and stripping it would turn one into a well-formed F33D3R Number
// once in every ten attempts — so the person would be told their contact was
// unreachable instead of that they pasted the wrong thing.
func isNumberSeparator(b byte) bool {
	return b == '-' || b == ' ' || b == '_' || b == '.'
}

// luhnSum folds a run of ASCII digits right to left, doubling every second one
// and casting out nines from the doubled value. It reports false if any byte is
// not a digit.
//
// One function serves both directions, exactly as in the Rust definition:
// nothing here recomputes a check digit, and the doubling position is derived
// from the distance to the right-hand end rather than from the length — which is
// the classic way a hand-written Luhn drifts when a format's length changes.
func luhnSum(digits []byte) (int, bool) {
	sum := 0
	for i := len(digits) - 1; i >= 0; i-- {
		b := digits[i]
		if b < '0' || b > '9' {
			return 0, false
		}
		v := int(b - '0')
		if (len(digits)-1-i)%2 == 1 {
			v *= 2
			if v > 9 {
				v -= 9
			}
		}
		sum += v
	}
	return sum, true
}

// numberLegacyCheckValue is the mod-37 check value of a legacy payload.
// Iterative, so no wide integer arithmetic is needed.
func numberLegacyCheckValue(payload []byte) (int, bool) {
	acc := 0
	for _, b := range payload {
		v := strings.IndexByte(numberLegacyAlphabet, b)
		if v < 0 {
			return 0, false
		}
		acc = (acc*32 + v) % 37
	}
	return acc, true
}

// groupNumber renders symbols as XXXX-XXXX-…: 4-4-4 for a Number, 4-4-5 for a
// legacy one.
func groupNumber(symbols []byte) string {
	return string(symbols[0:4]) + "-" + string(symbols[4:8]) + "-" + string(symbols[8:])
}

// canonicalNumber folds, strips and validates caller input, returning the
// canonical 0412-8837-2919 form. It accepts spaces, hyphens, underscores, full
// stops, any case, the confusable letters, and the fully namespaced number:
// form — everything a person might reasonably type after being told a Number out
// loud. It accepts a legacy Crockford Number in exactly the same ways.
//
// It reports false for anything that is not a Number at all. It never reports
// anything about whether a well-formed Number belongs to somebody.
func canonicalNumber(input string) (string, bool) {
	body := strings.TrimSpace(input)
	if len(body) > numberInputMax {
		return "", false
	}
	if len(body) > len(numberNamespace) &&
		strings.EqualFold(body[:len(numberNamespace)], numberNamespace) &&
		body[len(numberNamespace)] == ':' {
		body = body[len(numberNamespace)+1:]
	}

	// Byte-wise, so a multi-byte character can never land mid-symbol: its bytes
	// simply fail the alphabet check.
	symbols := make([]byte, 0, numberLegacyTotalLen)
	for i := 0; i < len(body); i++ {
		if isNumberSeparator(body[i]) {
			continue
		}
		symbols = append(symbols, foldNumberSymbol(body[i]))
	}

	switch len(symbols) {
	case numberTotalLen:
		sum, ok := luhnSum(symbols)
		if !ok || sum%10 != 0 {
			return "", false
		}
		return groupNumber(symbols), true
	case numberLegacyTotalLen:
		for _, b := range symbols {
			if strings.IndexByte(numberLegacyAlphabet, b) < 0 {
				return "", false
			}
		}
		expected, ok := numberLegacyCheckValue(symbols[:numberLegacyPayloadLen])
		if !ok {
			return "", false
		}
		if numberLegacyCheckAlphabet[expected] != symbols[numberLegacyPayloadLen] {
			return "", false
		}
		return groupNumber(symbols), true
	default:
		return "", false
	}
}

// isLegacyNumber reports whether a canonical Number is one of the base32 Numbers
// minted before the digit format.
//
// Owner-facing only. It exists so somebody holding an older Number can be shown
// that it is older and choose to mint a new one — never so a resolver can tell
// the two apart, which it has no endpoint to ask and no reason to know.
func isLegacyNumber(number string) bool {
	n := 0
	for i := 0; i < len(number); i++ {
		if !isNumberSeparator(number[i]) {
			n++
		}
	}
	return n == numberLegacyTotalLen
}

// ── Number → conversation ────────────────────────────────────────────────────

// handleCreateConvoByNumber starts (or reuses) a 1:1 conversation with whoever a
// F33D3R Number resolves to, if that Number's policy permits it. It is the exact
// counterpart of handleCreateConvo on the @handle path: same target pane, same
// conversation-creation function, same sidebar refresh.
//
// POST /messages/new-number  (form: number, capability, note)
func (h *Handler) handleCreateConvoByNumber(w http.ResponseWriter, r *http.Request) {
	started := time.Now()
	user := h.userFromRequest(w, r)
	if user == nil || user.PIALID == "" {
		http.Error(w, "unauthorized", http.StatusUnauthorized)
		return
	}

	// Every return below passes through here. A Number lookup that answered
	// faster because it did less work would say what it did, so none of them do.
	gate := func(state string) {
		holdFloor(started, numberResolveFloor)
		h.renderPartial(w, "gnosis_number_gate", map[string]interface{}{
			"PIALID": user.PIALID, "State": state})
	}

	number, wellFormed := canonicalNumber(r.FormValue("number"))
	if !wellFormed {
		gate("malformed")
		return
	}
	note := strings.TrimSpace(r.FormValue("note"))
	if len(note) > 280 {
		note = note[:280]
	}

	outcome, err := h.evaluateContact(r.Context(), user, contactQuery{
		Number:     number,
		Capability: strings.TrimSpace(r.FormValue("capability")),
		Note:       note,
	})
	if err != nil {
		log.Printf("[gnosis] contact decision by Number for pial %s: %v", user.PIALID, err)
		gate("unavailable")
		return
	}
	// The one notification pipeline, reached the one way: if a request was
	// opened, the person it landed on hears about it here and nowhere else.
	h.notifyContactRequest(user, outcome)

	if outcome.Decision != "allow" || outcome.TargetPIAL == "" {
		// "request" is the only outcome worth distinguishing to the caller,
		// because they caused it. Everything else — unknown, retired, closed,
		// capability_only without a link — is one indistinguishable refusal.
		if outcome.Decision == "request" {
			gate("request")
			return
		}
		gate("refused")
		return
	}

	account := dbpkg.AccountForPIAL(h.db, outcome.TargetPIAL)
	if account == "" || account == user.ID {
		gate("refused")
		return
	}
	convoID, err := h.ensureDirectConversation(user, account, outcome.TargetPIAL)
	if err != nil {
		log.Printf("[gnosis] opening conversation by Number for pial %s: %v", user.PIALID, err)
		gate("unavailable")
		return
	}

	holdFloor(started, numberResolveFloor)
	// Identical to the @handle path from here: refresh the sidebar, return the
	// thread. The identity behind the Number surfaces now, and not before.
	w.Header().Set("HX-Trigger", "gnosis-refresh")
	h.renderThread(w, user, convoID)
}

// ── The recipient's side ─────────────────────────────────────────────────────

// facetGnosisContactRequests draws the pending contact requests that landed on
// the viewer, inside the messaging surface — where somebody who has just been
// asked for a conversation will actually be looking.
//
// GET /facets/messages_requests
func (h *Handler) facetGnosisContactRequests(w http.ResponseWriter, r *http.Request) {
	user := h.userFromRequest(w, r)
	if user == nil || user.PIALID == "" {
		http.Error(w, "unauthorized", http.StatusUnauthorized)
		return
	}
	rows, err := h.pendingContactRequests(r.Context(), user.PIALID)
	if err != nil {
		log.Printf("[gnosis] contact requests for pial %s: %v", user.PIALID, err)
		h.renderPartial(w, "gnosis_contact_requests", map[string]interface{}{
			"PIALID": user.PIALID, "Unavailable": true})
		return
	}
	h.renderPartial(w, "gnosis_contact_requests", map[string]interface{}{
		"PIALID": user.PIALID, "Requests": rows})
}

// pendingContactRequests reads the requests waiting on one identity from the
// brain that owns them, and names the requesters this brain already knows.
//
// A requester with no account here stays anonymous rather than being dropped:
// somebody is asking either way, and a row the recipient cannot see is a
// decision they cannot make.
func (h *Handler) pendingContactRequests(ctx context.Context, pialID string) ([]contactRequestRow, error) {
	var payload struct {
		Requests []struct {
			ID            string `json:"id"`
			RequesterPIAL string `json:"requester_pial"`
			Note          string `json:"note"`
			CreatedAt     string `json:"created_at"`
		} `json:"requests"`
	}
	if err := h.callElohim(ctx, http.MethodGet,
		"/v1/contact/requests/"+url.PathEscape(pialID), nil, &payload); err != nil {
		return nil, err
	}
	rows := make([]contactRequestRow, 0, len(payload.Requests))
	for _, req := range payload.Requests {
		row := contactRequestRow{ID: req.ID, Note: req.Note, When: req.CreatedAt}
		if account := dbpkg.AccountForPIAL(h.db, req.RequesterPIAL); account != "" {
			if u, err := dbpkg.GetUserByID(h.db, account); err == nil && u != nil {
				row.Handle = u.Handle
				row.Name = u.DisplayName
				// A face to go with the name. A client that draws its own row
				// needs it; the Facet draws initials from the handle and simply
				// does not read this.
				row.Avatar = u.AvatarURL
			}
		}
		rows = append(rows, row)
	}
	return rows, nil
}
