package handler

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// ── The shape of a Number ────────────────────────────────────────────────────

// numberConformanceCases reads the corpus that manhattan/src/number.rs — the
// authoritative definition of this format — generates from its own behaviour.
//
// This is the drift guard. The Go mirror in messages_number.go is hand-written,
// and two implementations of one format will eventually disagree unless one of
// them is mechanically held to the other. Every case below is the Rust
// definition's own answer, so a mirror that differs by one digit, one separator,
// one folded letter or one check rule fails here rather than in production, at
// the moment somebody's real Number stops resolving.
//
// Regenerate after any change to the format:
//
//	UPDATE_NUMBER_CONFORMANCE=1 cargo test -p manhattan conformance
func numberConformanceCases(t *testing.T) (accepted [][2]string, refused []string) {
	t.Helper()
	path := filepath.Join("..", "..", "..", "manhattan", "number.conformance")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading the Number conformance corpus at %s: %v\n"+
			"This file is generated by manhattan/src/number.rs and is what stops the "+
			"Go mirror of the Number format from drifting away from it.", path, err)
	}
	for _, line := range strings.Split(string(raw), "\n") {
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.Split(line, "\t")
		switch parts[0] {
		case "OK":
			if len(parts) != 3 {
				t.Fatalf("malformed OK line in the corpus: %q", line)
			}
			accepted = append(accepted, [2]string{parts[1], parts[2]})
		case "NO":
			if len(parts) != 2 {
				t.Fatalf("malformed NO line in the corpus: %q", line)
			}
			refused = append(refused, parts[1])
		default:
			t.Fatalf("unknown verdict in the corpus: %q", line)
		}
	}
	return accepted, refused
}

// The whole drift guard, in one test: every case the Rust definition generated
// must produce the same answer here.
func TestCanonicalNumberAgreesWithTheRustDefinitionCaseForCase(t *testing.T) {
	accepted, refused := numberConformanceCases(t)
	if len(accepted) < 400 || len(refused) < 200 {
		t.Fatalf("the corpus is too small to prove anything: %d accepted, %d refused",
			len(accepted), len(refused))
	}
	for _, tc := range accepted {
		got, ok := canonicalNumber(tc[0])
		if !ok {
			t.Fatalf("the Rust definition accepts %q; the Go mirror refused it", tc[0])
		}
		if got != tc[1] {
			t.Fatalf("%q: Rust canonicalises to %q, the Go mirror to %q", tc[0], tc[1], got)
		}
	}
	for _, in := range refused {
		if got, ok := canonicalNumber(in); ok {
			t.Fatalf("the Rust definition refuses %q; the Go mirror accepted it as %q", in, got)
		}
	}
}

// Real Numbers, minted by Manhattan on a running stack and pinned here by hand.
// The corpus above proves the two implementations agree; these prove they agree
// about what a real allocation actually looks like, which a generator on its own
// cannot.
var liveMintedNumbers = []string{
	"0098-7754-8744",
	"9470-7363-5478",
	"6871-6349-1446",
	"4603-4757-1321",
	"4812-1630-4537",
}

func TestCanonicalNumberAcceptsEveryFormAPersonCanType(t *testing.T) {
	for _, want := range liveMintedNumbers {
		bare := strings.ReplaceAll(want, "-", "")
		for _, in := range []string{
			want,
			bare,
			bare[0:4] + " " + bare[4:8] + " " + bare[8:12],
			bare[0:4] + "." + bare[4:8] + "." + bare[8:12],
			"  " + want + "  ",
			"number:" + want,
			bare[0:6] + "_" + bare[6:12],
		} {
			got, ok := canonicalNumber(in)
			if !ok {
				t.Fatalf("%q was refused; a Number written down from speech must still resolve", in)
			}
			if got != want {
				t.Fatalf("%q canonicalised to %q, want %q", in, got, want)
			}
		}
	}
}

// Crockford's confusable folding is what lets a Number survive being written
// down: I and L read as 1, O reads as 0. Somebody copying twelve digits off a
// badge writes the letters their handwriting produces, and the folded result is
// still digits.
func TestCanonicalNumberFoldsConfusableSymbols(t *testing.T) {
	// 0098-7754-8744 with its zeros written as the letter O, exactly as somebody
	// copying twelve digits off a badge in a hurry writes them.
	for _, in := range []string{"OO98-7754-8744", "oo98 7754 8744", "OO98775 48744"} {
		got, ok := canonicalNumber(in)
		if !ok || got != "0098-7754-8744" {
			t.Fatalf("%q folded to %q ok=%v, want 0098-7754-8744", in, got, ok)
		}
	}
	// A legacy Number carries both foldings at once, exactly as somebody copying
	// it off a badge would write them.
	for _, in := range []string{"O1AB-CDEF-GHJKG", "0IAB-CDEF-GHJKG", "OLAB CDEF GHJKG", "olabcdefghjkg"} {
		got, ok := canonicalNumber(in)
		if !ok || got != "01AB-CDEF-GHJKG" {
			t.Fatalf("%q folded to %q ok=%v, want 01AB-CDEF-GHJKG", in, got, ok)
		}
	}
}

func TestCanonicalNumberRefusesWhatIsNotANumber(t *testing.T) {
	cases := map[string]string{
		"empty":                             "",
		"too short":                         "366158592 80",
		"eleven digits":                     "36615859280",
		"thirteen digits":                   "3661585928099",
		"a handle":                          "@someone",
		"bad check digit":                   "3661-5859-2808",
		"a letter that is not a confusable": "3661-5859-280X",
		"multi-byte characters":             "3661-5859-280é",
		"absurdly long":                     strings.Repeat("1", 200),
		"namespace but no value":            "number:",
		"legacy, bad check":                 "96M1-XPA3-345TT",
		"legacy check-only U":               "96M1-XPA3-345TU",
	}
	for name, in := range cases {
		if got, ok := canonicalNumber(in); ok {
			t.Fatalf("%s (%q) was accepted as %q", name, in, got)
		}
	}
}

// A pasted telephone number must be named as a mistake, not refused as if the
// person it belongs to had turned the caller away. Keeping the + means an E.164
// number can never be mistaken for a F33D3R Number — which it would be one time
// in ten if the + were stripped as punctuation.
func TestCanonicalNumberRefusesAPastedTelephoneNumber(t *testing.T) {
	for _, in := range []string{"+441234567890", "+1 415 555 0132", "(415) 555-0132", "+12025550143"} {
		if got, ok := canonicalNumber(in); ok {
			t.Fatalf("a telephone number %q was accepted as a F33D3R Number %q", in, got)
		}
	}
}

// The check digit is what makes a transcription error cost arithmetic instead
// of a lookup. Every single-digit corruption of a valid Number, in every
// position, must be caught here at the edge, without the policy authority ever
// being asked.
func TestCanonicalNumberCatchesEverySingleDigitTypo(t *testing.T) {
	checked := 0
	for _, valid := range liveMintedNumbers {
		bare := []byte(strings.ReplaceAll(valid, "-", ""))
		for i := range bare {
			for d := byte('0'); d <= '9'; d++ {
				if d == bare[i] {
					continue
				}
				corrupted := make([]byte, len(bare))
				copy(corrupted, bare)
				corrupted[i] = d
				if _, ok := canonicalNumber(string(corrupted)); ok {
					t.Fatalf("a single-digit typo was accepted: %s", corrupted)
				}
				checked++
			}
		}
	}
	if checked != len(liveMintedNumbers)*numberTotalLen*9 {
		t.Fatalf("only %d corruptions were checked", checked)
	}
}

// Luhn's one boundary, measured here as it is measured in the Rust definition:
// every adjacent transposition is caught EXCEPT the pair 09/90, which Luhn is
// blind to. The gap is exactly one pair wide, and this test fails if it ever
// becomes two.
func TestCanonicalNumberCatchesEveryAdjacentTranspositionExceptZeroNine(t *testing.T) {
	checked := 0
	for _, valid := range liveMintedNumbers {
		bare := []byte(strings.ReplaceAll(valid, "-", ""))
		for i := 0; i+1 < len(bare); i++ {
			if bare[i] == bare[i+1] {
				continue
			}
			if (bare[i] == '0' && bare[i+1] == '9') || (bare[i] == '9' && bare[i+1] == '0') {
				continue // the blind spot, exercised deliberately below
			}
			swapped := make([]byte, len(bare))
			copy(swapped, bare)
			swapped[i], swapped[i+1] = swapped[i+1], swapped[i]
			if _, ok := canonicalNumber(string(swapped)); ok {
				t.Fatalf("a transposition outside the blind spot was accepted: %s", swapped)
			}
			checked++
		}
	}
	if checked < 20 {
		t.Fatalf("only %d transpositions were checked", checked)
	}
}

// numberWithZeroNinePair is a valid Number constructed to carry an adjacent
// 0 and 9, because a minted one may not. Luhn cannot tell 09 from 90 — doubling
// 0 and doubling 9 differ by exactly nine, which its casting-out step erases.
const numberWithZeroNinePair = "4091-2883-7294"

// The boundary itself, asserted rather than left to luck. If this ever starts
// being CAUGHT, the mirror has stopped being Luhn and has drifted from the Rust
// definition; if a second pair joins it, the property has widened silently.
func TestLuhnsBlindSpotIsExactlyTheZeroNinePairAndNothingElse(t *testing.T) {
	bare := []byte(strings.ReplaceAll(numberWithZeroNinePair, "-", ""))
	if _, ok := canonicalNumber(string(bare)); !ok {
		t.Fatalf("%q must itself be a valid Number", numberWithZeroNinePair)
	}
	found := 0
	for i := 0; i+1 < len(bare); i++ {
		if !((bare[i] == '0' && bare[i+1] == '9') || (bare[i] == '9' && bare[i+1] == '0')) {
			continue
		}
		swapped := make([]byte, len(bare))
		copy(swapped, bare)
		swapped[i], swapped[i+1] = swapped[i+1], swapped[i]
		if _, ok := canonicalNumber(string(swapped)); !ok {
			t.Fatalf("09/90 is Luhn's blind spot; %s was caught, so this is not Luhn", swapped)
		}
		found++
	}
	if found == 0 {
		t.Fatal("the constructed Number no longer carries an adjacent 0 and 9")
	}
}

// A Number somebody has already shared is a promise. The base32 Numbers minted
// before the digit format keep resolving for ever — the two shapes are disjoint
// by length, so nothing had to be retired, reminted or migrated to make room.
func TestLegacyNumbersMintedBeforeTheDigitFormatStillResolve(t *testing.T) {
	for _, legacy := range []string{"96M1-XPA3-345TS", "EGCC-BPEY-K9KBP", "01AB-CDEF-GHJKG"} {
		got, ok := canonicalNumber(legacy)
		if !ok || got != legacy {
			t.Fatalf("a Number minted before the digit format stopped resolving: %q -> %q ok=%v",
				legacy, got, ok)
		}
		if !isLegacyNumber(got) {
			t.Fatalf("%q must be recognisable to its OWNER as an older Number", got)
		}
	}
	for _, current := range liveMintedNumbers {
		if isLegacyNumber(current) {
			t.Fatalf("%q is a current Number and must not be marked as legacy", current)
		}
	}
}

// ── The gate ─────────────────────────────────────────────────────────────────

// The security property this whole lane rests on: an unknown Number and a
// retired one must be one outcome, not two. Both arrive here as "refused", and
// the fragment must be byte-identical — a single helpful word about which it was
// would undo the enumeration defence at the last possible layer.
func TestNumberGateCannotDistinguishAnUnknownNumberFromARetiredOne(t *testing.T) {
	tmpl := partialSet(t, "_gnosis_number_gate.html")

	// Both an unresolved Number and a retired one produce decision "deny" from
	// the authority, which this surface renders as the single "refused" state.
	unknown := render(t, tmpl, "gnosis_number_gate", map[string]interface{}{
		"PIALID": "abc", "State": "refused"})
	retired := render(t, tmpl, "gnosis_number_gate", map[string]interface{}{
		"PIALID": "abc", "State": "refused"})
	if unknown != retired {
		t.Fatal("an unknown Number and a retired one rendered differently")
	}
	for _, leak := range []string{"unknown", "retired", "revoked", "closed", "does not exist", "no longer"} {
		if strings.Contains(strings.ToLower(unknown), leak) {
			t.Fatalf("the refusal leaked why it refused: %q", leak)
		}
	}
	// A refusal must not name anybody either — not a handle, not a display name.
	if strings.Contains(unknown, "@") {
		t.Fatal("a refusal disclosed a handle")
	}
}

func TestNumberGateRendersEveryOutcomeHonestly(t *testing.T) {
	tmpl := partialSet(t, "_gnosis_number_gate.html")

	malformed := render(t, tmpl, "gnosis_number_gate", map[string]interface{}{
		"PIALID": "abc", "State": "malformed"})
	if !strings.Contains(malformed, "not a F33D3R Number") {
		t.Fatal("a mistyped Number must be named as one, not silently refused")
	}
	if !strings.Contains(malformed, "0412 8837 2919") {
		t.Fatal("a malformed-Number error must show the shape being asked for")
	}
	// And the shape it shows must be a real one. An example that did not itself
	// satisfy the check digit would teach people to type something this very
	// surface then refuses.
	if _, ok := canonicalNumber("0412 8837 2919"); !ok {
		t.Fatal("the example shown to somebody who mistyped is not itself a valid Number")
	}

	request := render(t, tmpl, "gnosis_number_gate", map[string]interface{}{
		"PIALID": "abc", "State": "request"})
	if !strings.Contains(request, "Your request is waiting") {
		t.Fatal("a pending contact request must say so")
	}

	unavailable := render(t, tmpl, "gnosis_number_gate", map[string]interface{}{
		"PIALID": "abc", "State": "unavailable"})
	if strings.Contains(strings.ToLower(unavailable), "not reachable") {
		t.Fatal("an unreachable policy authority must not be reported to the user as a refusal")
	}
	if !strings.Contains(unavailable, "Nobody was contacted") {
		t.Fatal("an unavailable authority must say that nothing was sent")
	}

	// Every state carries the facet id, or the fragment cannot be located for
	// mutation.
	for _, out := range []string{malformed, request, unavailable} {
		if !strings.Contains(out, `data-facet-id="facet:f33d3r:contact:abc:number_gate"`) {
			t.Fatal("facet id missing or malformed")
		}
	}
}

// The four gate states must be four distinct sentences — otherwise "malformed"
// and "refused" collapse and a mistyped Number reads as a rejection.
func TestNumberGateStatesAreDistinct(t *testing.T) {
	tmpl := partialSet(t, "_gnosis_number_gate.html")
	seen := map[string]string{}
	for _, state := range []string{"malformed", "request", "refused", "unavailable"} {
		out := render(t, tmpl, "gnosis_number_gate", map[string]interface{}{
			"PIALID": "abc", "State": state})
		if prior, dup := seen[out]; dup {
			t.Fatalf("states %q and %q render identically", prior, state)
		}
		seen[out] = state
	}
}

// On F33D3R a contact is a mutual follow. There is no contacts list, no address
// book, no friend table — so no surface in this lane may imply that one exists,
// and a knock that is waiting to be answered must never read as a rejection.
func TestNumberLaneNeverInventsAContactsList(t *testing.T) {
	tmpl := partialSet(t, "_gnosis_number_gate.html", "_gnosis_contact_requests.html")

	surfaces := []string{
		render(t, tmpl, "gnosis_number_gate", map[string]interface{}{"PIALID": "abc", "State": "malformed"}),
		render(t, tmpl, "gnosis_number_gate", map[string]interface{}{"PIALID": "abc", "State": "request"}),
		render(t, tmpl, "gnosis_number_gate", map[string]interface{}{"PIALID": "abc", "State": "refused"}),
		render(t, tmpl, "gnosis_number_gate", map[string]interface{}{"PIALID": "abc", "State": "unavailable"}),
		render(t, tmpl, "gnosis_contact_requests", map[string]interface{}{
			"PIALID": "abc", "Requests": []contactRequestRow{{ID: "r1", Handle: "dana"}}}),
	}
	// "contact request" and "contact link" are the authority's own names for a
	// knock and for a bearer capability; neither is a set anyone is added to.
	// A list, a book or a roster would be.
	for _, out := range surfaces {
		lower := strings.ToLower(out)
		for _, invented := range []string{
			"contacts list", "your contacts", "add to contacts", "address book",
			"friend list", "friends list", "contact list", "add contact",
		} {
			if strings.Contains(lower, invented) {
				t.Fatalf("a surface invented a contacts set: %q", invented)
			}
		}
	}

	// The knock, specifically: a request is the recipient's to answer, and the
	// sender must not be told they were turned away.
	knock := surfaces[1]
	if !strings.Contains(knock, "not a refusal") {
		t.Fatal("a contact request must say plainly that it is not a refusal")
	}
	for _, rejection := range []string{"not reachable", "not accepting", "denied", "declined", "rejected"} {
		if strings.Contains(strings.ToLower(knock), rejection) {
			t.Fatalf("a knock was worded as a rejection: %q", rejection)
		}
	}

	// And it must not name which wall the sender met. Naming the policy would
	// turn the knock into a disclosure of how the recipient has locked their door.
	for _, policy := range []string{"followers", "mutuals", "number_only", "capability_only", "closed", "mutual follow"} {
		if strings.Contains(strings.ToLower(knock), policy) {
			t.Fatalf("a knock disclosed the policy that produced it: %q", policy)
		}
	}
}

// ── The recipient's side ─────────────────────────────────────────────────────

func TestContactRequestsFacetShowsWhoIsAskingAndOffersBothAnswers(t *testing.T) {
	tmpl := partialSet(t, "_gnosis_contact_requests.html")
	out := render(t, tmpl, "gnosis_contact_requests", map[string]interface{}{
		"PIALID": "abc",
		"Requests": []contactRequestRow{
			{ID: "r1", Handle: "dana", Name: "Dana", Note: "met you at the fair"},
			{ID: "r2"},
		},
	})
	if !strings.Contains(out, `data-facet-id="facet:f33d3r:identity:abc:contact_requests"`) {
		t.Fatal("facet id missing or malformed")
	}
	if !strings.Contains(out, "Dana") || !strings.Contains(out, "@dana") {
		t.Fatal("a requester this brain knows must be named")
	}
	if !strings.Contains(out, "met you at the fair") {
		t.Fatal("the requester's note must be shown — it is what the decision rests on")
	}
	if !strings.Contains(out, "Someone") {
		t.Fatal("a requester with no local account must still be answerable, not dropped")
	}
	// The copy must hold under all six policies, so it may not claim who gets
	// through without asking — that depends on the policy on the Number, which
	// this facet deliberately does not read.
	if !strings.Contains(out, "declining tells them nothing") {
		t.Fatal("the recipient must be told that declining is silent")
	}
	for _, policy := range []string{"followers", "mutuals", "number_only", "capability_only"} {
		if strings.Contains(strings.ToLower(out), policy) {
			t.Fatalf("the requests facet named a policy it does not read: %q", policy)
		}
	}
	if strings.Count(out, `name="accept" value="1"`) != 2 ||
		strings.Count(out, `name="accept" value="0"`) != 2 {
		t.Fatal("every request must offer both an accept and a decline")
	}
	// The decision itself belongs to one handler. This facet must not invent a
	// second endpoint for it.
	if strings.Count(out, "/identity/contact/requests/decide") != 8 {
		t.Fatal("requests are decided through the one endpoint that owns that decision")
	}
}

func TestContactRequestsFacetStaysQuietWhenNobodyIsWaiting(t *testing.T) {
	tmpl := partialSet(t, "_gnosis_contact_requests.html")
	empty := render(t, tmpl, "gnosis_contact_requests", map[string]interface{}{"PIALID": "abc"})
	if strings.Contains(empty, "Asking to reach you") {
		t.Fatal("an empty request list must not render a heading over nothing")
	}
	if !strings.Contains(empty, `data-facet-id="facet:f33d3r:identity:abc:contact_requests"`) {
		t.Fatal("the facet root must exist even when empty, or it cannot be mutated later")
	}

	down := render(t, tmpl, "gnosis_contact_requests", map[string]interface{}{
		"PIALID": "abc", "Unavailable": true})
	if !strings.Contains(down, "unavailable") {
		t.Fatal("an unreachable authority must be said out loud, not rendered as 'no requests'")
	}
}
